import { RepositoryError } from '../../utils/error-handling.js';
import { Images } from './models/images.model.js';

export const getAllRepository = async () => {
    try {
        return await Images.find();
    } catch (err) {
        throw new RepositoryError(err.message, 500);
    }
};

export const getImageServiceRepository = async (projections, populateProps) => {
    try {
        return await Images.find()
            .select(projections)
            .populate(populateProps);
    } catch (err) {
        throw new RepositoryError(err.message, 500);
    }
};

export const getOneRepository = async (id) => {
    try {
        return await Images.findOne({ _id: id });
    } catch (err) {
        throw new RepositoryError(err.message, 500);
    }
};

export const createRepository = async (body) => {
    try {
        const created = new Images(body);
        await created.save();

        return created;
    } catch (err) {
        throw new RepositoryError(err.message, 500);
    }
};

export const deleteRepository = async (id) => {
    try {
        await Images.deleteOne({ _id: id });
        return { id };
    } catch (err) {
        throw new RepositoryError(err.message, 500);
    }
};
